/**
 * Generated by `python -m pathwise.cli_fixtures`. Do not edit by hand.
 *
 * Real output from the deterministic engines over the real seed graph, not
 * invented sample data - so the UI is designed against what the system
 * actually produces, including the awkward parts.
 */

import type { Dashboard, Resource, Roadmap } from "@/lib/types";

export const ROADMAP_FIXTURE: Roadmap = {
  "id": "rm_demo",
  "title": "Path to Backpropagation",
  "summary": "13 steps from Probability Fundamentals to Backpropagation, about 45 hours. 9 prerequisites were removed because you have already demonstrated them. 2 more were shortened to reviews, saving about 6 hours.",
  "goalText": "I want to understand how neural networks actually learn.",
  "nodes": [
    {
      "conceptId": "16f802ac-f805-5a0a-bf19-aad459c7ba9a",
      "slug": "probability-fundamentals",
      "name": "Probability Fundamentals",
      "domain": "mathematics",
      "difficulty": 2,
      "estimatedMinutes": 210,
      "status": "not_started",
      "nodeType": "topic",
      "orderIndex": 0,
      "dependsOn": [],
      "rationale": "Needed for Random Variables and Supervised Learning Fundamentals.",
      "mastery": null
    },
    {
      "conceptId": "6ee2393e-b51f-5ab2-a143-b60926ba893c",
      "slug": "partial-derivatives",
      "name": "Partial Derivatives",
      "domain": "mathematics",
      "difficulty": 3,
      "estimatedMinutes": 180,
      "status": "not_started",
      "nodeType": "topic",
      "orderIndex": 1,
      "dependsOn": [],
      "rationale": "Needed for Gradients and Jacobians.",
      "mastery": {
        "alpha": 3.1,
        "beta": 4.9,
        "mastery": 0.3875,
        "confidence": 0.6,
        "evidenceCount": 3
      }
    },
    {
      "conceptId": "c4636b11-598c-5931-8ebd-abb915d4bd8d",
      "slug": "chain-rule",
      "name": "The Chain Rule",
      "domain": "mathematics",
      "difficulty": 3,
      "estimatedMinutes": 150,
      "status": "recommended",
      "nodeType": "topic",
      "orderIndex": 2,
      "dependsOn": [],
      "rationale": "Needed for Gradients and Jacobians and Backpropagation.",
      "mastery": null
    },
    {
      "conceptId": "dfd1111e-68ea-5e2e-a403-899248c4bb39",
      "slug": "matrix-operations",
      "name": "Matrix Operations",
      "domain": "mathematics",
      "difficulty": 2,
      "estimatedMinutes": 72,
      "status": "not_started",
      "nodeType": "review",
      "orderIndex": 3,
      "dependsOn": [],
      "rationale": "You have already shown some command of this, so it is a 72-minute review rather than the full 240 minutes.",
      "mastery": {
        "alpha": 9.8,
        "beta": 2.2,
        "mastery": 0.8167,
        "confidence": 0.7143,
        "evidenceCount": 5
      }
    },
    {
      "conceptId": "e0bbd170-192f-5042-ba98-a5826aaa42de",
      "slug": "numpy-fundamentals",
      "name": "NumPy Fundamentals",
      "domain": "machine-learning",
      "difficulty": 2,
      "estimatedMinutes": 72,
      "status": "not_started",
      "nodeType": "review",
      "orderIndex": 4,
      "dependsOn": [],
      "rationale": "You have already shown some command of this, so it is a 72-minute review rather than the full 240 minutes.",
      "mastery": {
        "alpha": 3.0,
        "beta": 1.0,
        "mastery": 0.75,
        "confidence": 0.3333,
        "evidenceCount": 1
      }
    },
    {
      "conceptId": "82239385-6782-5104-8d92-310fdec9070a",
      "slug": "gradients-and-jacobians",
      "name": "Gradients and Jacobians",
      "domain": "mathematics",
      "difficulty": 4,
      "estimatedMinutes": 210,
      "status": "locked",
      "nodeType": "topic",
      "orderIndex": 5,
      "dependsOn": [
        "6ee2393e-b51f-5ab2-a143-b60926ba893c",
        "c4636b11-598c-5931-8ebd-abb915d4bd8d"
      ],
      "rationale": "Needed for Gradient Descent and Backpropagation.",
      "mastery": null
    },
    {
      "conceptId": "7fdf80b2-ba30-5957-9311-f74d6a8c641e",
      "slug": "supervised-learning-fundamentals",
      "name": "Supervised Learning Fundamentals",
      "domain": "machine-learning",
      "difficulty": 3,
      "estimatedMinutes": 240,
      "status": "locked",
      "nodeType": "topic",
      "orderIndex": 6,
      "dependsOn": [
        "e0bbd170-192f-5042-ba98-a5826aaa42de",
        "16f802ac-f805-5a0a-bf19-aad459c7ba9a"
      ],
      "rationale": "Needed for Loss Functions and Model Evaluation Metrics.",
      "mastery": null
    },
    {
      "conceptId": "e28ec471-8e76-59ce-acb8-3c8a0ee1b005",
      "slug": "optimization-fundamentals",
      "name": "Optimisation Fundamentals",
      "domain": "mathematics",
      "difficulty": 3,
      "estimatedMinutes": 240,
      "status": "locked",
      "nodeType": "topic",
      "orderIndex": 7,
      "dependsOn": [
        "82239385-6782-5104-8d92-310fdec9070a"
      ],
      "rationale": "Needed for Constrained Optimisation and Gradient Descent.",
      "mastery": null
    },
    {
      "conceptId": "74b50cfc-9508-5d2b-a19e-27490e04bfec",
      "slug": "gradient-descent",
      "name": "Gradient Descent",
      "domain": "mathematics",
      "difficulty": 3,
      "estimatedMinutes": 240,
      "status": "locked",
      "nodeType": "topic",
      "orderIndex": 8,
      "dependsOn": [
        "82239385-6782-5104-8d92-310fdec9070a",
        "e28ec471-8e76-59ce-acb8-3c8a0ee1b005"
      ],
      "rationale": "Needed for Linear Regression and Neural Network Fundamentals.",
      "mastery": null
    },
    {
      "conceptId": "adf120c1-8a5a-517d-8e2e-0b8f7bf0bab1",
      "slug": "linear-regression",
      "name": "Linear Regression",
      "domain": "machine-learning",
      "difficulty": 3,
      "estimatedMinutes": 270,
      "status": "locked",
      "nodeType": "topic",
      "orderIndex": 9,
      "dependsOn": [
        "7fdf80b2-ba30-5957-9311-f74d6a8c641e",
        "74b50cfc-9508-5d2b-a19e-27490e04bfec",
        "dfd1111e-68ea-5e2e-a403-899248c4bb39"
      ],
      "rationale": "Needed for Logistic Regression and Regularisation.",
      "mastery": null
    },
    {
      "conceptId": "2b874aa8-df7e-5eb9-ab0e-0857dc9de25c",
      "slug": "logistic-regression",
      "name": "Logistic Regression",
      "domain": "machine-learning",
      "difficulty": 3,
      "estimatedMinutes": 240,
      "status": "locked",
      "nodeType": "topic",
      "orderIndex": 10,
      "dependsOn": [
        "adf120c1-8a5a-517d-8e2e-0b8f7bf0bab1"
      ],
      "rationale": "Needed for Support Vector Machines and Neural Network Fundamentals.",
      "mastery": null
    },
    {
      "conceptId": "d2c8864f-6bc9-5d8f-91c8-ccf7863c1a44",
      "slug": "neural-network-fundamentals",
      "name": "Neural Network Fundamentals",
      "domain": "machine-learning",
      "difficulty": 4,
      "estimatedMinutes": 300,
      "status": "locked",
      "nodeType": "topic",
      "orderIndex": 11,
      "dependsOn": [
        "2b874aa8-df7e-5eb9-ab0e-0857dc9de25c",
        "74b50cfc-9508-5d2b-a19e-27490e04bfec",
        "dfd1111e-68ea-5e2e-a403-899248c4bb39"
      ],
      "rationale": "Needed for Activation Functions and PyTorch Fundamentals.",
      "mastery": null
    },
    {
      "conceptId": "9266426d-d0a0-5f26-ad19-fc742802b6da",
      "slug": "backpropagation",
      "name": "Backpropagation",
      "domain": "machine-learning",
      "difficulty": 4,
      "estimatedMinutes": 300,
      "status": "locked",
      "nodeType": "topic",
      "orderIndex": 12,
      "dependsOn": [
        "82239385-6782-5104-8d92-310fdec9070a",
        "c4636b11-598c-5931-8ebd-abb915d4bd8d",
        "d2c8864f-6bc9-5d8f-91c8-ccf7863c1a44"
      ],
      "rationale": "Needed for Training Deep Networks.",
      "mastery": null
    }
  ],
  "edges": [
    {
      "source": "6ee2393e-b51f-5ab2-a143-b60926ba893c",
      "target": "82239385-6782-5104-8d92-310fdec9070a",
      "strength": 1.0
    },
    {
      "source": "c4636b11-598c-5931-8ebd-abb915d4bd8d",
      "target": "82239385-6782-5104-8d92-310fdec9070a",
      "strength": 0.9
    },
    {
      "source": "e0bbd170-192f-5042-ba98-a5826aaa42de",
      "target": "7fdf80b2-ba30-5957-9311-f74d6a8c641e",
      "strength": 0.9
    },
    {
      "source": "16f802ac-f805-5a0a-bf19-aad459c7ba9a",
      "target": "7fdf80b2-ba30-5957-9311-f74d6a8c641e",
      "strength": 0.8
    },
    {
      "source": "82239385-6782-5104-8d92-310fdec9070a",
      "target": "e28ec471-8e76-59ce-acb8-3c8a0ee1b005",
      "strength": 0.9
    },
    {
      "source": "82239385-6782-5104-8d92-310fdec9070a",
      "target": "74b50cfc-9508-5d2b-a19e-27490e04bfec",
      "strength": 1.0
    },
    {
      "source": "e28ec471-8e76-59ce-acb8-3c8a0ee1b005",
      "target": "74b50cfc-9508-5d2b-a19e-27490e04bfec",
      "strength": 1.0
    },
    {
      "source": "7fdf80b2-ba30-5957-9311-f74d6a8c641e",
      "target": "adf120c1-8a5a-517d-8e2e-0b8f7bf0bab1",
      "strength": 1.0
    },
    {
      "source": "74b50cfc-9508-5d2b-a19e-27490e04bfec",
      "target": "adf120c1-8a5a-517d-8e2e-0b8f7bf0bab1",
      "strength": 0.9
    },
    {
      "source": "dfd1111e-68ea-5e2e-a403-899248c4bb39",
      "target": "adf120c1-8a5a-517d-8e2e-0b8f7bf0bab1",
      "strength": 0.9
    },
    {
      "source": "adf120c1-8a5a-517d-8e2e-0b8f7bf0bab1",
      "target": "2b874aa8-df7e-5eb9-ab0e-0857dc9de25c",
      "strength": 1.0
    },
    {
      "source": "2b874aa8-df7e-5eb9-ab0e-0857dc9de25c",
      "target": "d2c8864f-6bc9-5d8f-91c8-ccf7863c1a44",
      "strength": 1.0
    },
    {
      "source": "74b50cfc-9508-5d2b-a19e-27490e04bfec",
      "target": "d2c8864f-6bc9-5d8f-91c8-ccf7863c1a44",
      "strength": 1.0
    },
    {
      "source": "dfd1111e-68ea-5e2e-a403-899248c4bb39",
      "target": "d2c8864f-6bc9-5d8f-91c8-ccf7863c1a44",
      "strength": 1.0
    },
    {
      "source": "82239385-6782-5104-8d92-310fdec9070a",
      "target": "9266426d-d0a0-5f26-ad19-fc742802b6da",
      "strength": 1.0
    },
    {
      "source": "c4636b11-598c-5931-8ebd-abb915d4bd8d",
      "target": "9266426d-d0a0-5f26-ad19-fc742802b6da",
      "strength": 1.0
    },
    {
      "source": "d2c8864f-6bc9-5d8f-91c8-ccf7863c1a44",
      "target": "9266426d-d0a0-5f26-ad19-fc742802b6da",
      "strength": 1.0
    }
  ],
  "skipped": [
    {
      "slug": "derivatives",
      "name": "Derivatives",
      "mastery": 0.86,
      "evidenceCount": 6
    },
    {
      "slug": "functions-and-graphs",
      "name": "Functions and Graphs",
      "mastery": 0.938,
      "evidenceCount": 7
    },
    {
      "slug": "limits-and-continuity",
      "name": "Limits and Continuity",
      "mastery": 0.929,
      "evidenceCount": 6
    },
    {
      "slug": "programming-basics",
      "name": "Programming Basics",
      "mastery": 0.944,
      "evidenceCount": 8
    },
    {
      "slug": "python-control-flow",
      "name": "Control Flow",
      "mastery": 0.944,
      "evidenceCount": 8
    },
    {
      "slug": "python-data-structures",
      "name": "Python Data Structures",
      "mastery": 0.938,
      "evidenceCount": 7
    },
    {
      "slug": "python-functions",
      "name": "Functions and Scope",
      "mastery": 0.944,
      "evidenceCount": 8
    },
    {
      "slug": "python-syntax-and-types",
      "name": "Python Syntax and Core Types",
      "mastery": 0.944,
      "evidenceCount": 8
    },
    {
      "slug": "vectors-and-spaces",
      "name": "Vectors and Vector Spaces",
      "mastery": 0.929,
      "evidenceCount": 6
    }
  ],
  "compressed": [
    {
      "slug": "matrix-operations",
      "name": "Matrix Operations",
      "mastery": 0.817,
      "originalMinutes": 240,
      "reviewMinutes": 72
    },
    {
      "slug": "numpy-fundamentals",
      "name": "NumPy Fundamentals",
      "mastery": 0.75,
      "originalMinutes": 240,
      "reviewMinutes": 72
    }
  ],
  "pacing": {
    "totalMinutes": 2724,
    "hoursPerWeek": 8.0,
    "estimatedWeeks": 5.7,
    "meetsDeadline": null,
    "requiredHoursPerWeek": null
  },
  "warnings": [],
  "revisionCount": 1
};

export const DASHBOARD_FIXTURE: Dashboard = {
  "next": {
    "slug": "chain-rule",
    "name": "The Chain Rule",
    "kind": "new",
    "estimatedMinutes": 150,
    "difficulty": 3,
    "score": 0.514,
    "decidingFactor": "goal_relevance",
    "explanation": "The Chain Rule is next \u2014 1 step from the goal. About 2.5 hours at difficulty 3/5.",
    "factors": [
      {
        "name": "readiness",
        "value": 1.0,
        "weight": 0.25,
        "contribution": 0.25,
        "detail": "comfortably clears its prerequisites (margin 0.26)"
      },
      {
        "name": "goal_relevance",
        "value": 0.5,
        "weight": 0.3,
        "contribution": 0.15,
        "detail": "1 step from the goal"
      },
      {
        "name": "difficulty_fit",
        "value": 0.6397,
        "weight": 0.1,
        "contribution": 0.064,
        "detail": "difficulty 3/5 against a demonstrated level of 4.4/5"
      },
      {
        "name": "momentum",
        "value": 1.0,
        "weight": 0.05,
        "contribution": 0.05,
        "detail": "continues in mathematics"
      },
      {
        "name": "review_debt",
        "value": 0.0,
        "weight": 0.2,
        "contribution": 0.0,
        "detail": "not due for review"
      },
      {
        "name": "remediation",
        "value": 0.0,
        "weight": 0.1,
        "contribution": 0.0,
        "detail": "not a remediation target"
      }
    ],
    "alternatives": [
      {
        "slug": "partial-derivatives",
        "name": "Partial Derivatives",
        "score": 0.464
      },
      {
        "slug": "probability-fundamentals",
        "name": "Probability Fundamentals",
        "score": 0.389
      }
    ]
  },
  "roadmapTitle": "Path to Backpropagation",
  "stepsTotal": 13,
  "stepsCompleted": 0,
  "hoursStudied": 51.2,
  "hoursRemaining": 45.4,
  "estimatedWeeks": 5.7,
  "byDomain": [
    {
      "domain": "machine-learning",
      "mastery": 0.75,
      "conceptsMeasured": 1
    },
    {
      "domain": "mathematics",
      "mastery": 0.793,
      "conceptsMeasured": 6
    },
    {
      "domain": "programming",
      "mastery": 0.942,
      "conceptsMeasured": 5
    }
  ],
  "weakest": [
    {
      "slug": "partial-derivatives",
      "name": "Partial Derivatives",
      "mastery": 0.388
    },
    {
      "slug": "numpy-fundamentals",
      "name": "NumPy Fundamentals",
      "mastery": 0.75
    },
    {
      "slug": "matrix-operations",
      "name": "Matrix Operations",
      "mastery": 0.817
    }
  ],
  "dueForReview": [],
  "recentRevisions": [
    {
      "revisionNo": 1,
      "createdAt": "2026-08-28T14:12:00Z",
      "explanation": "You scored 48% on Gradients and Jacobians. The Chain Rule is what it builds on, and that looks like where the gap is. A 45-minute section on it now comes first, so you reach Gradients and Jacobians prepared.",
      "trigger": {
        "kind": "assessment_failed",
        "concept": "gradients-and-jacobians",
        "name": "Gradients and Jacobians",
        "score": 0.48,
        "attempt": 1,
        "detail": ""
      },
      "mutations": [
        {
          "type": "insert_remediation",
          "name": "The Chain Rule",
          "estimatedMinutes": 45
        },
        {
          "type": "insert_remediation",
          "name": "Partial Derivatives",
          "estimatedMinutes": 45
        }
      ]
    }
  ]
};

export const RESOURCES_FIXTURE: Record<string, Resource[]> = {
  "probability-fundamentals": [
    {
      "title": "Seeing Theory",
      "url": "https://seeing-theory.brown.edu/",
      "type": "interactive",
      "publisher": "seeing-theory.brown.edu",
      "durationMinutes": 180,
      "difficulty": 2,
      "why": "Seeing Theory \u2014 difficulty 2/5, pitched just above your current level (1.0/5 measured)."
    },
    {
      "title": "MIT 6.041: Probabilistic Systems Analysis",
      "url": "https://ocw.mit.edu/courses/6-041-probabilistic-systems-analysis-and-applied-probability-fall-2010/",
      "type": "course",
      "publisher": "ocw.mit.edu",
      "durationMinutes": 2400,
      "difficulty": 4,
      "why": "MIT 6.041: Probabilistic Systems Analysis \u2014 a course resource."
    }
  ],
  "partial-derivatives": [
    {
      "title": "Khan Academy: Multivariable Calculus",
      "url": "https://www.khanacademy.org/math/multivariable-calculus",
      "type": "course",
      "publisher": "khanacademy.org",
      "durationMinutes": 900,
      "difficulty": 3,
      "why": "Khan Academy: Multivariable Calculus \u2014 difficulty 3/5, pitched just above your current level (2.5/5 measured)."
    },
    {
      "title": "MIT 18.02: Multivariable Calculus",
      "url": "https://ocw.mit.edu/courses/18-02-multivariable-calculus-fall-2007/",
      "type": "course",
      "publisher": "ocw.mit.edu",
      "durationMinutes": 2000,
      "difficulty": 4,
      "why": "MIT 18.02: Multivariable Calculus \u2014 a course resource."
    }
  ],
  "chain-rule": [
    {
      "title": "3Blue1Brown: Essence of Calculus",
      "url": "https://www.3blue1brown.com/topics/calculus",
      "type": "video",
      "publisher": "3blue1brown.com",
      "durationMinutes": 200,
      "difficulty": 2,
      "why": "3Blue1Brown: Essence of Calculus \u2014 difficulty 2/5, pitched just above your current level (1.0/5 measured)."
    }
  ],
  "matrix-operations": [
    {
      "title": "NumPy Linear Algebra Reference",
      "url": "https://numpy.org/doc/stable/reference/routines.linalg.html",
      "type": "documentation",
      "publisher": "numpy.org",
      "durationMinutes": 60,
      "difficulty": 3,
      "why": "NumPy Linear Algebra Reference \u2014 difficulty 3/5, below your current level (4.3/5 measured)."
    },
    {
      "title": "MIT 18.06: Linear Algebra",
      "url": "https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/",
      "type": "course",
      "publisher": "ocw.mit.edu",
      "durationMinutes": 2400,
      "difficulty": 4,
      "why": "MIT 18.06: Linear Algebra \u2014 difficulty 4/5, below your current level (4.3/5 measured)."
    },
    {
      "title": "3Blue1Brown: Essence of Linear Algebra",
      "url": "https://www.3blue1brown.com/topics/linear-algebra",
      "type": "video",
      "publisher": "3blue1brown.com",
      "durationMinutes": 180,
      "difficulty": 2,
      "why": "3Blue1Brown: Essence of Linear Algebra \u2014 a video resource."
    }
  ],
  "numpy-fundamentals": [
    {
      "title": "NumPy Broadcasting",
      "url": "https://numpy.org/doc/stable/user/basics.broadcasting.html",
      "type": "documentation",
      "publisher": "numpy.org",
      "durationMinutes": 45,
      "difficulty": 3,
      "why": "NumPy Broadcasting \u2014 difficulty 3/5, below your current level (4.0/5 measured)."
    },
    {
      "title": "NumPy: the absolute basics for beginners",
      "url": "https://numpy.org/doc/stable/user/absolute_beginners.html",
      "type": "documentation",
      "publisher": "numpy.org",
      "durationMinutes": 120,
      "difficulty": 2,
      "why": "NumPy: the absolute basics for beginners \u2014 written specifically about this topic."
    }
  ],
  "gradients-and-jacobians": [
    {
      "title": "Khan Academy: Multivariable Calculus",
      "url": "https://www.khanacademy.org/math/multivariable-calculus",
      "type": "course",
      "publisher": "khanacademy.org",
      "durationMinutes": 900,
      "difficulty": 3,
      "why": "Khan Academy: Multivariable Calculus \u2014 a course resource."
    },
    {
      "title": "MIT 18.02: Multivariable Calculus",
      "url": "https://ocw.mit.edu/courses/18-02-multivariable-calculus-fall-2007/",
      "type": "course",
      "publisher": "ocw.mit.edu",
      "durationMinutes": 2000,
      "difficulty": 4,
      "why": "MIT 18.02: Multivariable Calculus \u2014 a course resource."
    }
  ],
  "supervised-learning-fundamentals": [
    {
      "title": "scikit-learn User Guide",
      "url": "https://scikit-learn.org/stable/user_guide.html",
      "type": "documentation",
      "publisher": "scikit-learn.org",
      "durationMinutes": 1200,
      "difficulty": 3,
      "why": "scikit-learn User Guide \u2014 a documentation resource."
    },
    {
      "title": "An Introduction to Statistical Learning",
      "url": "https://www.statlearning.com/",
      "type": "book",
      "publisher": "statlearning.com",
      "durationMinutes": 2400,
      "difficulty": 3,
      "why": "An Introduction to Statistical Learning \u2014 a book resource."
    }
  ],
  "optimization-fundamentals": [
    {
      "title": "3Blue1Brown: Gradient Descent",
      "url": "https://www.3blue1brown.com/lessons/gradient-descent",
      "type": "video",
      "publisher": "3blue1brown.com",
      "durationMinutes": 25,
      "difficulty": 3,
      "why": "3Blue1Brown: Gradient Descent \u2014 a video resource."
    },
    {
      "title": "SciPy Optimization Reference",
      "url": "https://docs.scipy.org/doc/scipy/reference/optimize.html",
      "type": "documentation",
      "publisher": "docs.scipy.org",
      "durationMinutes": 90,
      "difficulty": 3,
      "why": "SciPy Optimization Reference \u2014 a documentation resource."
    },
    {
      "title": "Convex Optimization",
      "url": "https://web.stanford.edu/~boyd/cvxbook/",
      "type": "book",
      "publisher": "web.stanford.edu",
      "durationMinutes": 3000,
      "difficulty": 5,
      "why": "Convex Optimization \u2014 a book resource."
    }
  ],
  "gradient-descent": [
    {
      "title": "3Blue1Brown: Gradient Descent",
      "url": "https://www.3blue1brown.com/lessons/gradient-descent",
      "type": "video",
      "publisher": "3blue1brown.com",
      "durationMinutes": 25,
      "difficulty": 3,
      "why": "3Blue1Brown: Gradient Descent \u2014 a video resource."
    },
    {
      "title": "3Blue1Brown: Neural Networks",
      "url": "https://www.3blue1brown.com/topics/neural-networks",
      "type": "video",
      "publisher": "3blue1brown.com",
      "durationMinutes": 120,
      "difficulty": 3,
      "why": "3Blue1Brown: Neural Networks \u2014 a video resource."
    }
  ],
  "linear-regression": [
    {
      "title": "scikit-learn User Guide",
      "url": "https://scikit-learn.org/stable/user_guide.html",
      "type": "documentation",
      "publisher": "scikit-learn.org",
      "durationMinutes": 1200,
      "difficulty": 3,
      "why": "scikit-learn User Guide \u2014 a documentation resource."
    },
    {
      "title": "An Introduction to Statistical Learning",
      "url": "https://www.statlearning.com/",
      "type": "book",
      "publisher": "statlearning.com",
      "durationMinutes": 2400,
      "difficulty": 3,
      "why": "An Introduction to Statistical Learning \u2014 a book resource."
    }
  ],
  "logistic-regression": [
    {
      "title": "scikit-learn User Guide",
      "url": "https://scikit-learn.org/stable/user_guide.html",
      "type": "documentation",
      "publisher": "scikit-learn.org",
      "durationMinutes": 1200,
      "difficulty": 3,
      "why": "scikit-learn User Guide \u2014 a documentation resource."
    },
    {
      "title": "An Introduction to Statistical Learning",
      "url": "https://www.statlearning.com/",
      "type": "book",
      "publisher": "statlearning.com",
      "durationMinutes": 2400,
      "difficulty": 3,
      "why": "An Introduction to Statistical Learning \u2014 a book resource."
    }
  ],
  "neural-network-fundamentals": [
    {
      "title": "3Blue1Brown: Neural Networks",
      "url": "https://www.3blue1brown.com/topics/neural-networks",
      "type": "video",
      "publisher": "3blue1brown.com",
      "durationMinutes": 120,
      "difficulty": 3,
      "why": "3Blue1Brown: Neural Networks \u2014 a video resource."
    },
    {
      "title": "Practical Deep Learning for Coders",
      "url": "https://course.fast.ai/",
      "type": "course",
      "publisher": "course.fast.ai",
      "durationMinutes": 2400,
      "difficulty": 3,
      "why": "Practical Deep Learning for Coders \u2014 a course resource."
    },
    {
      "title": "Deep Learning (Goodfellow, Bengio, Courville)",
      "url": "https://www.deeplearningbook.org/",
      "type": "book",
      "publisher": "deeplearningbook.org",
      "durationMinutes": 4000,
      "difficulty": 5,
      "why": "Deep Learning (Goodfellow, Bengio, Courville) \u2014 a book resource."
    }
  ]
};
